repos:
  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint (system)
        entry: bash -lc 'unset ANSIBLE_COLLECTIONS_PATHS; ANSIBLE_CONFIG=ansible/ansible.cfg ANSIBLE_COLLECTIONS_PATH=ansible/collections ansible-lint ansible/playbooks/site.yml'
        language: system
        files: ^ansible/

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c, .yamllint]
        files: ^ansible/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
