# Global exclude avoids touching vendored Galaxy collections
exclude: ^ansible/collections/

repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        # Limit yamllint to your code paths
        files: ^(ansible/(playbooks|roles|inventories|group_vars)/|\.github/workflows/|README\.md|\.yamllint|\.ansible-lint\.yml|ansible/ansible\.cfg)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        files: ^(ansible/(playbooks|roles|inventories|group_vars)/|\.github/workflows/|README\.md|.*\.ya?ml)$
      - id: trailing-whitespace
        files: ^(ansible/(playbooks|roles|inventories|group_vars)/|\.github/workflows/|README\.md|.*\.ya?ml)$
