---
- name: Reload nginx via systemd
  listen: "Reload nginx"
  become: true
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: ansible_service_mgr == 'systemd'

- name: Reload nginx via CLI
  listen: "Reload nginx"
  become: true
  ansible.builtin.command: nginx -s reload
  changed_when: false
  when: ansible_service_mgr != 'systemd'
