apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-media-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-media-api
  template:
    metadata:
      labels:
        app: demo-media-api
    spec:
      containers:
        - name: api
          image: ghcr.io/REPLACE_ME/demo-media-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
