---
# ansible/playbooks/site.yml

# 1) Load Balancer
- name: Configure load balancer
  hosts: lb
  become: true
  tags: [lb, nginx]
  roles:
    - role: nginx

# 2) Web nodes
- name: Configure web nodes
  hosts: web
  become: true
  gather_facts: true
  tags: [web]

  pre_tasks:
    - name: Gather facts (always)
      ansible.builtin.setup:
      tags: [always]

    - name: Ensure apt extended_states is writable (prevents apt-mark errors)
      ansible.builtin.file:
        path: /var/lib/apt/extended_states
        state: touch
        owner: root
        group: root
        mode: '0644'
      become: true
      tags: [zabbix]

    - name: Update apt cache early (robust)
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        lock_timeout: 60
      become: true
      tags: [always]

    - name: Ensure gnupg is present (safe for Zabbix repo tasks)
      ansible.builtin.apt:
        name: gnupg
        state: present
        force_apt_get: true
        lock_timeout: 60
      become: true
      tags: [zabbix]

  roles:
    - role: nginx
      tags: [nginx]
    - role: community.zabbix.zabbix_agent
      tags: [zabbix]
      vars:
        zabbix_agent_packages:
          - { name: zabbix-agent2, state: present }
          - { name: zabbix-get, state: present }
          - { name: zabbix-sender, state: present }
