replicaCount: 1
image:
  repository: demo-media-api
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
resources: {}
env: []
ingress:
  enabled: false
  className: ""
  hosts: []
  tls: []
