name: Lint
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_CONFIG: ansible/ansible.cfg
      # make the path absolute for the runner
      ANSIBLE_COLLECTIONS_PATH: ${{ github.workspace }}/ansible/collections
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install linters + Ansible Core
        run: |
          python -m pip install -U pip
          pip install --user ansible-core~=2.17 ansible-lint yamllint pre-commit
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Show versions (debug)
        run: |
          ansible --version || true
          ansible-lint --version
          python - <<'PY'
import ansible, sys
print("ansible", ansible.__version__, "| python", sys.version.split()[0])
PY

      - name: Run pre-commit
        run: pre-commit run --all-files
