name: Lint
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install linters
        run: |
          python -m pip install -U pip
          pip install --user pre-commit ansible-lint yamllint
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Run pre-commit
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
          ANSIBLE_COLLECTIONS_PATH: ansible/collections
        run: pre-commit run --all-files
