---
name: Lint
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      ANSIBLE_CONFIG: ansible/ansible.cfg
      ANSIBLE_COLLECTIONS_PATH: ${{ github.workspace }}/ansible/collections
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ansible & linters
        run: |
          python -m pip install -U pip
          pip install --user ansible-core ansible-lint yamllint
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Prepare Galaxy requirements (fallback)
        run: |
          set -e
          mkdir -p ansible/collections
          if [ ! -f ansible/collections/requirements.yml ]; then
            cat > ansible/collections/requirements.yml <<'REQ'
---
collections:
  - name: community.zabbix
REQ
          fi
          echo "Using requirements.yml:"
          cat ansible/collections/requirements.yml

      - name: Install Galaxy collections
        run: |
          ansible-galaxy collection install \
            -r ansible/collections/requirements.yml \
            -p "$ANSIBLE_COLLECTIONS_PATH"
          ansible-galaxy collection list

      - name: Lint (ansible-lint)
        run: ansible-lint -c .ansible-lint.yml ansible/playbooks/site.yml

      - name: YAML lint (project code only)
        run: |
          paths=(ansible/playbooks ansible/roles ansible/group_vars)
          keep=()
          for p in "${paths[@]}"; do [ -d "$p" ] && keep+=("$p"); done
          if [ "${#keep[@]}" -gt 0 ]; then
            yamllint -c .yamllint "${keep[@]}"
          else
            echo "No YAML paths to lint; skipping."
          fi
