---
name: Lint
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_CONFIG: ansible/ansible.cfg
      ANSIBLE_COLLECTIONS_PATH: ${{ github.workspace }}/ansible/collections
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ansible + linters
        run: |
          python -m pip install -U pip
          pip install --user ansible-core ansible-lint yamllint
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install Galaxy collections (community.zabbix)
        run: |
          mkdir -p "$ANSIBLE_COLLECTIONS_PATH"
          ansible-galaxy collection install -r ansible/collections/requirements.yml -p "$ANSIBLE_COLLECTIONS_PATH"
          echo "== Collections installed ==" && ansible-galaxy collection list

      - name: Run ansible-lint
        run: ansible-lint -v -c .ansible-lint.yml ansible/playbooks/site.yml

      - name: Run yamllint
        run: yamllint -c .yamllint ansible/playbooks ansible/roles ansible/group_vars
