---
name: Lint
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_CONFIG: ansible/ansible.cfg
      ANSIBLE_COLLECTIONS_PATH: ansible/collections
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ansible-core and linters
        run: |
          python -m pip install -U pip
          pip install --user ansible-core ansible-lint yamllint pre-commit
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Run pre-commit (ansible-lint + yamllint)
        run: pre-commit run --all-files --show-diff-on-failure
